name: CommentHub
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with test

    - name: Run Bandit
      run: |
        poetry run bandit -r api

    - name: Lint with flake8
      run: |
        poetry run flake8 api

    - name: Run tests with coverage
      run: |
        poetry run coverage run --source api -m pytest --disable-warnings
        poetry run coverage xml -o .qodana/code-coverage/coverage.xml

    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: py-coverage-data
        path: .qodana/code-coverage

    - name: Qodana Scan
      if: always()
      uses: JetBrains/qodana-action@v2024.1
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      with:
        args: "--linter,jetbrains/qodana-python:latest"
        pr-mode: false .
  Backend-Tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Install dependencies 
        working-directory: ./api
        run: poetry install
      - name: Run test coverage
        working-directory: .
        run: poetry run pytest --cov=app --cov-branch --cov-report term-missing --cov-fail-under=65 tests/
